# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: tweetWeather

provider:
    name: aws
    runtime: python3.12

    stage: dev
    region: us-east-1
    logRetentionInDays: 7

functions:
    weather:
        handler: tweet_weather.tweet_weather
        events:
        # GMT Time
            - schedule: rate(2 hours)
        maximumRetryAttempts: 0

custom:
    pythonRequirements:
        dockerizePip: true

package:
    exclude:
        - venv/**
        - .venv/**
        - env/**
        - node_modules/**
        - __pycache__/**
